version: '3'
services:
#  webapp:
#    container_name: web-app
#    build:
#      context: ./webapp
#      dockerfile: Dockerfile
  elasticsearch:
    build:
      context: ./ES
      dockerfile: Dockerfile
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    links:
      - elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring